/*
 * This source file was generated by the Gradle 'init' task
 */
package aoc.day01;

import org.junit.jupiter.api.Test;

import aoc.util.Input;

import static org.junit.jupiter.api.Assertions.*;

import java.util.List;

class Day01Test {
    @Test
    void part1() throws Exception {
        List<String> input = Input.read(1);
        assertEquals(Day01.solvePart1(input), 3);
    }

    @Test
    void part2() throws Exception {
        List<String> input = Input.read(1);
        assertEquals(Day01.solvePart2(input), 0);
    }
}
